### ISSUE TITLE
STOP blinking light?

### ISSUE THREAD

**Issue by timwilson235** [alextaujenis/RBD_Light#1]
Not so much an issue as a question: Once a light is set to blinking (using light.blink() ) what is the proper way (if any) to STOP the blinking?

(Apologies if there is a more appropriate way to ask a question than by filing an issue - I could not figure out how to just ask a question).

**Comment by alextaujenis** [comment]
That's a great question! I was going to say light.off() but that won't work (yet). Right now it would stop if you called light.blink(250,250,1); but that's a silly way to do things.

I'll patch this so you can call light.on() or light.off() and this will break the blink/fade loop.

**Comment by timwilson235** [comment]
Thanks for the reply and for the code improvement.

It would also be nice to have a way to stop your Timer...

On Sat, Nov 14, 2015 at 11:32 AM, Alex Taujenis notifications@github.com
wrote:

> That's a great question! I was going to say light.off() but that won't
> work (yet). Right now it would stop if you called light.blink(250,250,1);
> but that's a silly way to do things.
> 
> I'll patch this so you can call light.on() or light.off() and this will
> break the blink/fade loop.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/alextaujenis/RBD_Light/issues/1#issuecomment-156730990
> .

## 

"If I have not seen as far as other men, it is because giants have stood on
my shoulders"

**Comment by alextaujenis** [comment]
Ok, upgrade to Light v2.1.0 or later and you can stop blinking and fading by calling on(), off(), setBrightness(), or setBrightnessPercent(), (which is how it should have acted from the start). Thanks for reporting this! I also went and fixed a similar issue with the Motor library.

I started venturing down the timer.stop() method a while ago and it just didn't make sense. Maybe you can post some sample code (on how you want to use it) over in the Timer library [feature request area](https://github.com/alextaujenis/RBD_Timer/issues) and we can discuss it.
