### ISSUE TITLE
Using relays

### ISSUE THREAD

**Issue by Babaiko** [alextaujenis/RBD_Light#12]
Really good library works fine with LEDs. But it creates discomfort when using the relay module with blink function and switching on and off . Many of the relay module operates at a low signal. so the commands comes inverted.

There is a simple way to change the behaviour or to specify that the output inverted?
 Arduino MEGA 2560

**Comment by alextaujenis** [comment]
I don't plan on implementing an `inverse` feature for this library. Feel free to fork this project and implement for your own needs.
