### ISSUE TITLE
RBD Light Fading to specific brightness

### ISSUE THREAD

**Issue by brunofosi** [alextaujenis/RBD_Light#13]
Hi Alex, stumble upon your light and timer library! thank you for both, they are great and easy to use! can you please tellme if i can specify the brightness of the fading light? like 0->255 or instead 0->200? there is a .setBrightness() but i don't know how to use it with fade. thanks for the support

**Comment by alextaujenis** [comment]
The fade function on this library doesn't have a brightness modifier, it's only smart enough to go from 0 -> 255 as you mentioned. This library is ripe for a re-write, so I'll keep your suggestion for this improvement in mind.
