### ISSUE TITLE
Combine RBD_Light and RBD_Button

### ISSUE THREAD

**Issue by saspol** [alextaujenis/RBD_Light#3]
Hello, i tried use this libraries together and instantly have issues.
In my example i press the button and led is (probably)blinking.

```
setup () {
  BUTTON.invertReading();
  BUTTON.setDebounceTimeout(100);
  LED.blink(40,40);
}
loop () {
  if( BUTTON.isPressed() ) {
    LED.update();
  }
}
```

The problem is - led is stop blinking in random state. Sometimes is off, sometimes on and i cannot check state with `if(LED.isOn)` - it does not works. Ofcause i can turn off it with `analogWrite(LED, 0)` but this is not a point. I have Leonardo with latest Arduino IDE.

**Comment by saspol** [comment]
Like this also does not works - led dont blink at all.

```
loop () {
  if( BUTTON.isPressed() ) {
    LED.update();
  } else {
   LED.off();
}
}
```

**Comment by alextaujenis** [comment]
Hi @saspol,

From what I can tell you would like to blink a light if the button is pressed, then turn off the light if the button is released. We can write it like this:

``` arduino
#include <RBD_Timer.h>
#include <RBD_Light.h>
#include <RBD_Button.h>

RBD::Button button(2); // digital pin 2
RBD::Light  light(13); // internal led

void setup() {
  button.invertReading();
  button.setDebounceTimeout(100);
}

void loop() {
  light.update();

  if(button.onPressed()) {
    light.blink(40,40);
  }
  if(button.onReleased()) {
    light.off();
  }
}
```

The light.update() function should be called inside of loop, and is efficient enough that it doesn't need to be protected by an 'if' statement.

You should think of this more like a state machine. The onPressed() and onReleased() functions only fire once, and this is where we change the state of the light to blink or turn off.

I know I only made subtle changes to the way you were doing it, but give this a try and follow this pattern to use these libraries.

I should probably add this example to the website to show how to combine these two libraries.

**Comment by saspol** [comment]
Hi!

In my real example i have two switches and one button.
SWITCH1 - low light
SWITCH2 - high light
BUTTON - blinking which override both switches

And this construction also does not work - i see only one short blink on
press BUTTON.

loop() {
  LED.update();

  if ( BUTTON.onPressed() ) {
    LED.blink(40, 40);
  } else if (SWITCH2.isPressed()) {
    LED.on();
  } else if (SWITCH1.isPressed()) {
    LED.setBrightnessPercent(2);
  } else {
    LED.off();
  }
}

**Comment by saspol** [comment]
Sorry, FRONT_LAMPS_PWM replace with LED in this code.

Mitry

2016-01-26 12:17 GMT+05:30 Mitry <julleymitry@gmail.com>:

**Comment by alextaujenis** [comment]
You can edit comments by hitting the pencil icon at the top right of the comment box.

**Comment by alextaujenis** [comment]
You are using onPressed() and isPressed() interchangeably, but they don't act the same way.

Let's say the button is currently being held down:
- isPressed() will return true on each pass of the Arduino loop() (this means many times)
- onPressed() will return true once, then return false until the button is released and the pressed again (this means once)

isPressed() is for real-time actions, while onPressed() is for one-time events.

On to the next issue: you need to remove the if/else structure. This isn't a decision tree: it's a state machine.

``` arduino
void loop() {
  LED.update();

  if (BUTTON.onPressed()) {
    LED.blink(40, 40);
  }
  if (SWITCH1.onPressed()) {
    LED.setBrightnessPercent(20);
  }
  if (SWITCH2.onPressed()) {
    LED.on();
  }
  if(BUTTON.onReleased() || SWITCH1.onReleased() || SWITCH2.onReleased()) {
    LED.off();
  }
}
```

The last issue is that LED.setBrightnessPercent(2) will look really dim, almost as if it is off. Maybe you wanted LED.setBrightnessPercent(20) so I changed it.

**Comment by saspol** [comment]
The point of my if/else structure is priority BUTTON->SWITCH2->SWITCH1
Not necessary to check other switches position if BUTTON is pressed, just need to back previous state when it released. Your last code example completely have no logic, im not understand what you mean.

  LED.update();

  if (BUTTON.isPressed()) {
    LED.blink(40, 40);
  } else
  if (SWITCH2.isPressed()) {
    LED.on();
  } else
  if (SWITCH1.isPressed()) {
    LED.setBrightnessPercent(2);
  }
  if(BUTTON.isReleased() && SWITCH1.isReleased() && SWITCH2.isReleased()) {
    LED.off();
  }

This code do what i want. Thanx for help!

**Comment by alextaujenis** [comment]
* The Arduino loop runs thousands of times each second
* The code in your sketch is not using delay, you you must manage this like a state machine
* onPressed() will return true only ONCE. You must release the button and press it again to get another SINGLE true value out of it
* onPressed() only returns true ONCE so you can catch the event happening
* when you catch an event happening: you set the state of the light
* calling blink() on the light doesn't actually blink the light: it sets a variable inside of light that tells the light to act like it is blinking
* the light ACTUALLY blinks when you call light.update()
* you cannot use an if/else statement with onPressed() or onReleased(): their actions will only execute for a microsecond before the next Arduino loop comes around and they return false (this is by design)
* I can't explain this linearly to you; you have to understand many things to correctly implement this without delay
* Did you try running this code? If it does what you expect then maybe you should work backwards and try to understand what is happening with it:

```arduino
void loop() {
  LED.update();

  if (BUTTON.onPressed()) {
    LED.blink(40, 40);
  }
  if (SWITCH1.onPressed()) {
    LED.setBrightnessPercent(20);
  }
  if (SWITCH2.onPressed()) {
    LED.on();
  }
  if(BUTTON.onReleased() || SWITCH1.onReleased() || SWITCH2.onReleased()) {
    LED.off();
  }
}
```
