### ISSUE TITLE
Use RBD-Light with platformio

### ISSUE THREAD

**Issue by saspol** [alextaujenis/RBD_Light#6]
Hello!
I try to build this library on PlatformIO build system(platformio.org) and have this issue:
Can you please give me idea what this can means?

**Comment by saspol** [comment]
## [Mon Apr 25 00:56:42 2016] Processing esp12e (platform: espressif, board: esp12e, framework: arduino)

xtensa-lx106-elf-g++ -o .pioenvs/esp12e/src/main.o -c -fno-rtti -fno-exceptions -std=c++11 -Os -mlongcalls -mtext-section-literals -falign-functions=4 -ffunction-sectio
ns -fdata-sections -MMD -DF_CPU=80000000L -D__ets__ -DICACHE_FLASH -DESP8266 -DARDUINO_ARCH_ESP8266 -DARDUINO_ESP8266_ESP12 -DARDUINO=20100 -DPLATFORMIO=020806 -U__STRI
CT_ANSI__ -I/Users/mitry/.platformio/packages/framework-arduinoespressif/tools/sdk/include -I.pioenvs/esp12e/FrameworkArduino -I.pioenvs/esp12e/FrameworkArduinoVariant
-I.pioenvs/esp12e/RBD_Timer -I.pioenvs/esp12e/RBD_Light src/main.cpp
In file included from src/main.cpp:2:0:

.pioenvs/esp12e/RBD_Light/RBD_Light.h:51:17: error: macro "_max" requires 2 arguments, but only 1 given
void _max();
^
.pioenvs/esp12e/RBD_Light/RBD_Light.h:53:17: error: macro "_min" requires 2 arguments, but only 1 given
void _min();
^
.pioenvs/esp12e/RBD_Light/RBD_Light.h:51:12: error: variable or field '_max' declared void
void _max();
^
.pioenvs/esp12e/RBD_Light/RBD_Light.h:53:12: error: variable or field '_min' declared void
void _min();
^
xtensa-lx106-elf-g++ -o .pioenvs/esp12e/RBD_Timer/RBD_Timer.o -c -fno-rtti -fno-exceptions -std=c++11 -Os -mlongcalls -mtext-section-literals -falign-functions=4 -ffunc
tion-sections -fdata-sections -MMD -DF_CPU=80000000L -D__ets__ -DICACHE_FLASH -DESP8266 -DARDUINO_ARCH_ESP8266 -DARDUINO_ESP8266_ESP12 -DARDUINO=20100 -U__STRICT_ANSI__
 -I/Users/mitry/.platformio/packages/framework-arduinoespressif/tools/sdk/include -I.pioenvs/esp12e/FrameworkArduino -I.pioenvs/esp12e/FrameworkArduinoVariant -I.pioenv
s/esp12e/RBD_Timer -I.pioenvs/esp12e/RBD_Light .pioenvs/esp12e/RBD_Timer/RBD_Timer.cpp
scons: **\* [.pioenvs/esp12e/src/main.o] Error 1
xtensa-lx106-elf-g++ -o .pioenvs/esp12e/RBD_Light/RBD_Light.o -c -fno-rtti -fno-exceptions -std=c++11 -Os -mlongcalls -mtext-section-literals -falign-functions=4 -ffunc
tion-sections -fdata-sections -MMD -DF_CPU=80000000L -D__ets__ -DICACHE_FLASH -DESP8266 -DARDUINO_ARCH_ESP8266 -DARDUINO_ESP8266_ESP12 -DARDUINO=20100 -U__STRICT_ANSI__
 -I/Users/mitry/.platformio/packages/framework-arduinoespressif/tools/sdk/include -I.pioenvs/esp12e/FrameworkArduino -I.pioenvs/esp12e/FrameworkArduinoVariant -I.pioenv
s/esp12e/RBD_Timer -I.pioenvs/esp12e/RBD_Light .pioenvs/esp12e/RBD_Light/RBD_Light.cpp
In file included from .pioenvs/esp12e/RBD_Light/RBD_Light.cpp:8:0:

.pioenvs/esp12e/RBD_Light/RBD_Light.h:51:17: error: macro "_max" requires 2 arguments, but only 1 given
void _max();
^
.pioenvs/esp12e/RBD_Light/RBD_Light.h:53:17: error: macro "_min" requires 2 arguments, but only 1 given
void _min();
^
.pioenvs/esp12e/RBD_Light/RBD_Light.cpp:153:14: error: macro "_max" requires 2 arguments, but only 1 given
_max();
^
.pioenvs/esp12e/RBD_Light/RBD_Light.cpp:159:14: error: macro "_min" requires 2 arguments, but only 1 given
_min();
^
.pioenvs/esp12e/RBD_Light/RBD_Light.cpp:182:20: error: macro "_max" requires 2 arguments, but only 1 given
void Light::_max() {
^
.pioenvs/esp12e/RBD_Light/RBD_Light.cpp:216:20: error: macro "_min" requires 2 arguments, but only 1 given
void Light::_min() {
^
In file included from .pioenvs/esp12e/RBD_Light/RBD_Light.cpp:8:0:
.pioenvs/esp12e/RBD_Light/RBD_Light.h:51:12: error: variable or field '_max' declared void
void _max();
^
.pioenvs/esp12e/RBD_Light/RBD_Light.h:53:12: error: variable or field '_min' declared void
void _min();
^

.pioenvs/esp12e/RBD_Light/RBD_Light.cpp: In member function 'void RBD::Light::_fade()':
.pioenvs/esp12e/RBD_Light/RBD_Light.cpp:153:9: error: '_max' was not declared in this scope
_max();
^
.pioenvs/esp12e/RBD_Light/RBD_Light.cpp:159:9: error: '_min' was not declared in this scope
_min();
^
.pioenvs/esp12e/RBD_Light/RBD_Light.cpp: At global scope:
.pioenvs/esp12e/RBD_Light/RBD_Light.cpp:182:15: error: variable or field '_max' declared void
void Light::_max() {
^
.pioenvs/esp12e/RBD_Light/RBD_Light.cpp:183:5: error: expected primary-expression before 'if'
if(_shouldBeMax()) {
^
.pioenvs/esp12e/RBD_Light/RBD_Light.cpp:183:5: error: expected '}' before 'if'
.pioenvs/esp12e/RBD_Light/RBD_Light.cpp:264:1: error: expected '}' at end of input
}
^
scons: **\* [.pioenvs/esp12e/RBD_Light/RBD_Light.o] Error 1
========================= [ ERROR ] Took 1.25 seconds =========================

**Comment by proferom** [comment]
actually i have the same error on ESP based boards, but not on AVR.

**Comment by proferom** [comment]
to eliminate the error, modification of RBD_Light.h is needed:
#include <Arduino.h>
#undef _min
#undef _max

**Comment by alextaujenis** [comment]
@saspol I haven't tested this library with platformio. @proferom do you have any more context on this issue?

**Comment by alextaujenis** [comment]
Closed due to lack of information.
