### ISSUE TITLE
fade outside of the setup

### ISSUE THREAD

**Issue by MisterMedion** [alextaujenis/RBD_Light#7]
Hi

is it possible to use the fade-command in a other void as the setup-void?
im programming a LED controller. with a button, i increment a counter. with "while" i check the value of the counter and start different void's calles Programm. in Programm0 turn of all LED, in Programm1 i turn on 2 LED. In Programm2 2 LED's are blinking. this works great with your library. in Programm3 i would fade the 2 LED's. If i put the fade-command in this void.Programm3(), they won't fade.

I put my Arduino-Sourcecode in a Text-File an add it in the attatch.

Can you help me. Thanks a lot in forward.

[Neues Textdokument.txt](https://github.com/alextaujenis/RBD_Light/files/257700/Neues.Textdokument.txt)

**Comment by alextaujenis** [comment]
1. Every time you call light.fade() it will restart the fade cycle.
2. Light.fade() should be called only ONCE when Program3() starts running.
3. Light.update() actually does the work to change the brightness of the light (and should be called on every loop).

I can't simply change your sketch to make this work. If you use RBD_Button you could do something like this:

``` arduino
#include <RBD_Timer.h>  // https://github.com/alextaujenis/RBD_Timer
#include <RBD_Button.h> // https://github.com/alextaujenis/RBD_Button
#include <RBD_Light.h>  // https://github.com/alextaujenis/RBD_Light

RBD::Button button(2); // input pullup enabled by default
RBD::Light  light(13);

void setup() {}

void loop() {
  if(button.onPressed()) {
    light.fade(500,250,500,250);
  }

  if(button.onReleased()) {
    light.off();
  }

  light.update();
}
```

**Comment by MisterMedion** [comment]
Thanks for you awnser, but i still have the same Problem. Maybe it would be helpful if I explane you my Project: I would do a Light Controll for my RC Car. With a button i can jump through the several Programms. In the Programms (at least over 20 different Programms) i would define wich LED should be On or Blink or fade. every Programm should have a other "Light-Show".

I searching on the Web for some simple LED-Controll Librarys for Arduino and find your's. it works currently great. I do a V1.0 just with LED on/off and blinking. Here a short Video:
https://www.youtube.com/watch?v=nUNTt_LC6eE

In the next Step i would integrate the Fade-Feature. but as i try to show you, it doesn't work if i put it in a separate void. 

Here i will send you a simple sketch, how I would solve it in the best & simplest case. Maybe you can help me or give me a other walkthrough

Thank you a lot in forward, and sorry for my bad english-skils.
Also sorry for the bad formated post. i am new on github and i don't know how to put the programmcode in a nice format like you do.

kind regards
Patrick

``` arduino
#include <RBD_Timer.h>  // https://github.com/alextaujenis/RBD_Timer
#include <RBD_Button.h> // https://github.com/alextaujenis/RBD_Button
#include <RBD_Light.h>  // https://github.com/alextaujenis/RBD_Light

RBD::Button button(2); // input pullup enabled by default
RBD::Light  light(11);

int Counter = 0;


void setup() {}

void Programm1()
{
  light.fade(500,500,500,500);
}

void Programm2()
{
  light.fade(125,125,125,125);
  }


void loop() {



  if(button.onPressed()) {
    Counter++;
    delay(1000);
  }

while (Counter == 1)                                
      {
        Programm1();
        return;
      } 



  while (Counter == 2)                                
      {
        Programm2();
        return;
      } 

light.update();

}
```

**Comment by alextaujenis** [comment]
To format your code in Github you can do this:

``` arduino
void loop() {
  if(button.onPressed()) {
    Serial.println("button pressed");
  }
}
```

Which looks like this in the editor:
![screen shot 2016-06-01 at 1 44 14 pm](https://cloud.githubusercontent.com/assets/521443/15723286/f92ef182-27fe-11e6-981b-bae6a08016e1.png)

You press this key three times for the accent marks.
![687474703a2f2f696d672d666f746b692e79616e6465782e72752f6765742f353633312f39383939313933372e31312f305f39313932395f38646466653162625f6f726967](https://cloud.githubusercontent.com/assets/521443/15723382/64997ad2-27ff-11e6-9a33-bf6e49d9b694.gif)

You can read about markdown / code & syntax highlighting here: [https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting)

To answer your question, try using this sketch:

``` arduino
#include <RBD_Timer.h>  // https://github.com/alextaujenis/RBD_Timer
#include <RBD_Button.h> // https://github.com/alextaujenis/RBD_Button
#include <RBD_Light.h>  // https://github.com/alextaujenis/RBD_Light

RBD::Button button(2); // input pullup enabled by default
RBD::Light  light(11);

int counter = 0;
int maximum = 2;

void setup() {}

void loop() {
  if(button.onPressed()) {
    incrementCounter();
    runProgram();
  }
  light.update();
}

void incrementCounter() {
  if(counter == maximum) {
    counter = 1;
  } 
  else {
    counter++;
  }
}

void runProgram() {
  if(counter == 1) {
    program1();
  }
  if(counter == 2) {
    program2();
  }
}

void program1() {
  light.fade(500,500,500,500);
}

void program2() {
  light.fade(125,125,125,125);
}
```

**Comment by MisterMedion** [comment]
Ok, Thanks a lot for your support. your help will be great. Now i can finish my very cool project.
Also thanks for your tips about the comment-function in GitHub.
