### ISSUE TITLE
Fading strip UP or DOWN

### ISSUE THREAD

**Issue by dokterpasta** [alextaujenis/RBD_Light#9]
Hi,

I'm using an Arduino MEGA 2560 and I must say, I love your library. My LED-strips are fading and blinking perfectly! so great job!

But I was wondering, is there a way to fade up or down the led strips? Because at the moment, your library only supports fading up and down (repeating). 

At home, I have a Kodi client running and I made a plugin that will send a command to my Arduino so he can fade out or in the LED strips. I wanted to use your library to fade out or fade in the strips. Is there a simple way to accomplish this? Preferably with functions like FadeToBrightness(int) or FadeToBrightnessPercent(int)

Thanks,
Reggi

**Comment by alextaujenis** [comment]
This is a good suggestion. I don't plan on implementing this feature, however, feel free to open a pull request if you'd like to see this in the library.
